DROP TABLE RESREC;
DROP TABLE HSECOLL;
DROP TABLE BREAKTIME;
DROP TABLE MRMSG;
DROP TABLE MSMSG;
DROP TABLE ARTICLE;
DROP TABLE NEWS;
DROP TABLE NEWS_TYPE;
DROP TABLE ANN;
DROP TABLE QA;
DROP TABLE QA_TYPE;
DROP TABLE PROMO;
DROP TABLE COUPON;
DROP TABLE ADVERTISEMENT;
DROP TABLE FOLLOW_RTR;
DROP TABLE REPORTPRODUCT;
DROP TABLE REPORTREALTOR;
DROP TABLE ORDER_DETAIL;
DROP TABLE PRODUCT_ORDER;
DROP TABLE PRDIMG;
DROP TABLE PRD_COLLECTION;
DROP TABLE PRODUCT;
DROP TABLE PRD_CATEGORY;
DROP TABLE EMPLOYEE_AUTH;
DROP TABLE EMPLOYEE;
DROP TABLE BK_FUNCTION;
DROP TABLE SELLER;
DROP TABLE REALTOR;
DROP TABLE HOUSEIMAGES;
DROP TABLE HOUSEINFO;
DROP TABLE REALESTATE;
DROP TABLE MEMBER;

DROP SEQUENCE EMP_SEQ;
DROP SEQUENCE BKF_NO_SEQ;
DROP SEQUENCE RESR_SEQ;
DROP SEQUENCE SEQ_NEWS;
DROP SEQUENCE SEQ_ANN;
DROP SEQUENCE SEQ_QA;
DROP SEQUENCE SEQ_PRO;
DROP SEQUENCE SEQ_COU;
DROP SEQUENCE HOUSE_SEQUENCE;
DROP SEQUENCE HOUSEIMAGES_SEQUENCE;
DROP SEQUENCE ADVERTISEMENT_SEQUANCE;
DROP SEQUENCE PRDIMG_SEQ;
DROP SEQUENCE MEM_SEQ;
DROP SEQUENCE RE_SEQ;
DROP SEQUENCE RTR_SEQ;
DROP SEQUENCE SLR_SEQ;
DROP SEQUENCE PRDT_CATE_SEQ;
DROP SEQUENCE PD_SEQ;
DROP SEQUENCE RP_SEQ;
DROP SEQUENCE RR_SEQ;
DROP SEQUENCE PDO_NO_SEQ;

----------- 會員 ---------------------
CREATE TABLE MEMBER (
MEM_NO         VARCHAR2(10) NOT NULL,
MEM_ID         VARCHAR2(40) NOT NULL,
MEM_PSW        VARCHAR2(40) NOT NULL,
MEM_NAME       VARCHAR2(12),
MEM_ADDR       VARCHAR2(100),
SEARCH_STATE   VARCHAR2(10),
LOCK_STATE     VARCHAR2(10),
CONSTRAINT MEMBER_PK PRIMARY KEY(MEM_NO) );

CREATE SEQUENCE MEM_SEQ 
INCREMENT BY 1 
START WITH 1 
NOCACHE;

INSERT INTO MEMBER VALUES ('MB'||(LPAD(TO_CHAR(MEM_SEQ.NEXTVAL),8,'0')),'STEVEJOBS@GMAIL.COM','123456','賈伯斯','新北市萬里區一條路9號','ON','ON');
INSERT INTO MEMBER VALUES ('MB'||(LPAD(TO_CHAR(MEM_SEQ.NEXTVAL),8,'0')),'MICHAELJORDAN@GMAIL.COM','123456','喬丹','台北市內湖區灌籃路168號','ON','ON');
INSERT INTO MEMBER VALUES ('MB'||(LPAD(TO_CHAR(MEM_SEQ.NEXTVAL),8,'0')),'PETERWU@GMAIL.COM','123456','彼得吳','台北市大安區中大路8號','ON','ON');
INSERT INTO MEMBER VALUES ('MB'||(LPAD(TO_CHAR(MEM_SEQ.NEXTVAL),8,'0')),'BILLGATES@GMAIL.COM','123456','比爾蓋茲','桃園市中壢區中大路300號','ON','ON');


------------ 房仲公司 --------------
CREATE TABLE REALESTATE (
RE_NO         VARCHAR2(10) NOT NULL,
RE_NAME       VARCHAR2(40) NOT NULL,
CONSTRAINT RE_PK PRIMARY KEY(RE_NO) );

CREATE SEQUENCE RE_SEQ 
INCREMENT BY 1 
START WITH 1 
NOCACHE;

INSERT INTO REALESTATE VALUES ('RE'||(LPAD(TO_CHAR(RE_SEQ.NEXTVAL),8,'0')),'信義房屋');
INSERT INTO REALESTATE VALUES ('RE'||(LPAD(TO_CHAR(RE_SEQ.NEXTVAL),8,'0')),'永慶房屋');
INSERT INTO REALESTATE VALUES ('RE'||(LPAD(TO_CHAR(RE_SEQ.NEXTVAL),8,'0')),'東森房屋');


-------------- 房仲 --------------
CREATE TABLE REALTOR (
RTR_NO          VARCHAR2(10) NOT NULL,
RTR_ID          VARCHAR2(40) NOT NULL,
RTR_PSW         VARCHAR2(40) NOT NULL,
RTR_NAME        VARCHAR2(40),
RTR_PHOTO       BLOB,
RTR_AREA        VARCHAR2(40),
RTR_INTRO       CLOB,
RTR_IDNO        VARCHAR2(10),
RE_NO           VARCHAR2(10),
RTR_STATE       VARCHAR2(10),
CONSTRAINT RTR_ESTATE_FK FOREIGN KEY(RE_NO) REFERENCES REALESTATE(RE_NO),
CONSTRAINT RTR_PK PRIMARY KEY(RTR_NO) );

CREATE SEQUENCE RTR_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;

INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR01@GMAIL.COM', '123456', '葦小寶', '北投區', 'A108064497', 'RE00000001', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR02@GMAIL.COM', '123456', '王建民', '中正區', 'B123456789', 'RE00000002', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR03@GMAIL.COM', '123456', '林志玲', '士林區', 'X298765432', 'RE00000002', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR04@GMAIL.COM', '123456', '張三豐', '內湖區', 'D165432178', 'RE00000001', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR05@GMAIL.COM', '123456', '林大偉', '大安區', 'C132165491', 'RE00000002', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR06@GMAIL.COM', '123456', '李進財', '信義區', 'A198765432', 'RE00000001', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR07@GMAIL.COM', '123456', '趙德助', '萬華區', 'H147258369', 'RE00000002', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR08@GMAIL.COM', '123456', '張鈞甯', '中山區', 'X265432155', 'RE00000001', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR09@GMAIL.COM', '123456', '王小明', '大同區', 'A123466593', 'RE00000002', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR10@GMAIL.COM', '123456', '陳金鋒', '大安區', 'F136925874', 'RE00000003', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR11@GMAIL.COM', '123456', '連天邊', '信義區', 'H118754326', 'RE00000001', 'ON');
INSERT INTO REALTOR(RTR_NO, RTR_ID, RTR_PSW, RTR_NAME, RTR_AREA, RTR_IDNO, RE_NO, RTR_STATE)
VALUES('RT'||(LPAD(TO_CHAR(RTR_SEQ.NEXTVAL),8,'0')), 'BA104_RLTR12@GMAIL.COM', '123456', '楊美麗', '中正區', 'B213456789', 'RE00000001', 'ON');


-------------- 廠商 --------------
CREATE TABLE SELLER (
SLR_NO           VARCHAR2(10) NOT NULL,
SLR_NAME         VARCHAR2(40),
SLR_TAXID        VARCHAR2(10),
SLR_ID           VARCHAR2(40) NOT NULL,
SLR_PSW          VARCHAR2(40) NOT NULL,
SLR_CONTACT      VARCHAR2(40),
SLR_PHONE        VARCHAR2(10),
SLR_STATE        VARCHAR2(10),
SLR_INTRO        CLOB,
CONSTRAINT SLR_PK PRIMARY KEY(SLR_NO) );

CREATE SEQUENCE SLR_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;

INSERT INTO SELLER(SLR_NO, SLR_NAME, SLR_TAXID, SLR_ID, SLR_PSW, SLR_CONTACT, SLR_PHONE, SLR_STATE)
VALUES('SL'||(LPAD(TO_CHAR(SLR_SEQ.NEXTVAL),8,'0')), '宜家家居', '84309586', 'SALES@IKEA.COM', '123456', '李協達', '84128869', 'ON');
INSERT INTO SELLER(SLR_NO, SLR_NAME, SLR_TAXID, SLR_ID, SLR_PSW, SLR_CONTACT, SLR_PHONE, SLR_STATE)
VALUES('SL'||(LPAD(TO_CHAR(SLR_SEQ.NEXTVAL),8,'0')), '歐德傢俱', '70394175', 'SALES@ORDER.COM', '123456', '陳國都', '0800033988', 'ON');
INSERT INTO SELLER(SLR_NO, SLR_NAME, SLR_TAXID, SLR_ID, SLR_PSW, SLR_CONTACT, SLR_PHONE, SLR_STATE)
VALUES('SL'||(LPAD(TO_CHAR(SLR_SEQ.NEXTVAL),8,'0')), '特力屋', '89390488', 'SALES@HOLA.COM.TW', '123456', '何湯雄', '87915566', 'ON');
INSERT INTO SELLER(SLR_NO, SLR_NAME, SLR_TAXID, SLR_ID, SLR_PSW, SLR_CONTACT, SLR_PHONE, SLR_STATE)
VALUES('SL'||(LPAD(TO_CHAR(SLR_SEQ.NEXTVAL),8,'0')), '詩肯柚木', '89403884', 'SALES@SCANTEAK .COM.TW', '123456', '林福勤', '03-3180555', 'ON');


-------------- 商品類別 --------------
CREATE TABLE PRD_CATEGORY (
CATE_NO      VARCHAR2(10) NOT NULL,
CATE_NAME    VARCHAR2(100) NOT NULL,
CONSTRAINT PRDT_CATE_PK PRIMARY KEY(CATE_NO) );

CREATE SEQUENCE PRDT_CATE_SEQ 
INCREMENT BY 1 
START WITH 1 
NOCACHE;

INSERT INTO PRD_CATEGORY VALUES ('PC'||(LPAD(TO_CHAR(PRDT_CATE_SEQ.NEXTVAL),8,'0')),'桌子');
INSERT INTO PRD_CATEGORY VALUES ('PC'||(LPAD(TO_CHAR(PRDT_CATE_SEQ.NEXTVAL),8,'0')),'椅子');
INSERT INTO PRD_CATEGORY VALUES ('PC'||(LPAD(TO_CHAR(PRDT_CATE_SEQ.NEXTVAL),8,'0')),'櫃子');


-------------- 商品 --------------
CREATE TABLE PRODUCT (
PRD_NO          VARCHAR2(10) NOT NULL,
SLR_NO          VARCHAR2(10) NOT NULL,
CATE_NO         VARCHAR2(10) NOT NULL,
PRD_NAME        VARCHAR2(100) NOT NULL,
PRD_DESC        CLOB,
PRD_STOCK       NUMBER(6),
PRD_PRICE       NUMBER(10) NOT NULL,
PRD_STATE       VARCHAR2(10),
CONSTRAINT PRD_PK PRIMARY KEY(PRD_NO),
CONSTRAINT PRD_SL_FK FOREIGN KEY(SLR_NO) REFERENCES SELLER(SLR_NO),
CONSTRAINT PRD_CG_FK FOREIGN KEY(CATE_NO) REFERENCES PRD_CATEGORY(CATE_NO) );

CREATE SEQUENCE PD_SEQ
INCREMENT BY 1 
START WITH 1 
NOCACHE;

INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000001','KLIMPEN桌子, 灰色 淺灰色',62,8780,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000001','LINNMON/ALEX 桌子, 幾何圖案 藍色, 白色',73,3890,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000001','MALM 書桌/工作桌, 白色',87,3990,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000001','MALM L型書桌/工作桌, 棕色 實木貼皮, 梣木',46,3990,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000001','PAHL 書桌/工作桌附延伸層架, 白色, 粉紅色',59,3390,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000001','PAHL 書桌/工作桌附層架, 白色, 綠色',61,3390,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000002','EKEBOL 三人座沙發, KATORP 自然色',12,15900,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000002','EKTORP 三人座沙發, NORDVALLA 深米',7,13900,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000002','LANGFJALL 旋轉椅, GUNNARED 米色, 白色',28,4999,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000002','LANGFJALL 旋轉椅, GUNNARED 棕紅色, 白色',16,4999,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000002','MARKUS 旋轉椅, GLOSE 黑色 ROBUST 黑色',15,4990,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000002','SPORREN 旋轉椅, 白色, VISSLE 淺藍色',23,1799,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000002','STRANDMON 扶手椅, GILLHOV 彩色',38,7990,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000003','HURDAL 寢具櫃, 綠色',4,11900,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000003','KALLAX 層架組, 灰色, 木紋',19,2695,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000003','KALLAX-黑棕色 層架組附門片',26,2895,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000003','LIXHULT 收納組合, 紅色, 藍色',23,11900,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000003','PAX 衣櫃/衣櫥, 染白橡木紋, FARVIK 白色玻璃',3,30600,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000003','STUVA 衣櫃/衣櫥, 白色, 藍色',10,5690,'ON');
INSERT INTO PRODUCT(PRD_NO,SLR_NO,CATE_NO,PRD_NAME,PRD_STOCK,PRD_PRICE,PRD_STATE) VALUES('PD'||(LPAD(TO_CHAR(PD_SEQ.NEXTVAL),8,'0')),'SL00000001','PC00000003','STUVA 衣櫃/衣櫥, 白色, 粉紅色',14,5690,'ON');





-------- 收藏商品 (外來鍵 MEM_NO、PRD_NO 作為雙主鍵)-----------
CREATE TABLE PRD_COLLECTION (
MEM_NO        VARCHAR2(10) NOT NULL,
PRD_NO        VARCHAR2(10) NOT NULL,
PCTIME        TIMESTAMP,
CONSTRAINT MEM_PRD_PK PRIMARY KEY (MEM_NO,PRD_NO),
CONSTRAINT PC_MEM_FK FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO),
CONSTRAINT PC_PRD_FK FOREIGN KEY(PRD_NO) REFERENCES PRODUCT(PRD_NO) );
------------------------------
--收藏商品尚未 INSERT 假資料
------------------------------

CREATE TABLE EMPLOYEE (
EMP_NO VARCHAR2(10) NOT NULL,
EMP_ID VARCHAR2(40) NOT NULL,
EMP_PSW VARCHAR2(40) NOT NULL,
EMP_NAME VARCHAR2(40) NOT NULL,
EMP_LSTLOG TIMESTAMP,
EMP_BADLOG TIMESTAMP,
EMP_BADLOGTRY NUMBER(10) DEFAULT 0,
EMP_PHOTO BLOB,
EMP_STATE VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
EMP_NEWDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
CONSTRAINT EMP_NO_PK PRIMARY KEY(EMP_NO));



CREATE SEQUENCE EMP_SEQ
INCREMENT BY 1 
START WITH 1 
NOCACHE;

------INSERT先寫在這裡--------
INSERT INTO EMPLOYEE(EMP_NO, EMP_ID, EMP_PSW, EMP_NAME, EMP_STATE) VALUES('EM'||(LPAD(TO_CHAR
(EMP_SEQ.NEXTVAL),8,'0')), 'PETER@FORHOUSE.COM', '123456' ,'吳神', 'ACTIVE');
INSERT INTO EMPLOYEE(EMP_NO, EMP_ID, EMP_PSW, EMP_NAME, EMP_STATE) VALUES('EM'||(LPAD(TO_CHAR
(EMP_SEQ.NEXTVAL),8,'0')), 'YYY@FORHOUSE.COM', '123456' ,'楊宇茵', 'ACTIVE');
INSERT INTO EMPLOYEE(EMP_NO, EMP_ID, EMP_PSW, EMP_NAME, EMP_STATE) VALUES('EM'||(LPAD(TO_CHAR
(EMP_SEQ.NEXTVAL),8,'0')), 'DRAGON@FORHOUSE.COM', '123456' ,'趙子龍', 'ACTIVE');
------------------------------
CREATE TABLE BK_FUNCTION(
BKF_NO NUMBER(10),
BKF_NAME VARCHAR2(40) NOT NULL, 
BKF_DSB VARCHAR2(100) NOT NULL, 
BKF_STATE VARCHAR2(10) NOT NULL,
BKF_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
CONSTRAINT BKF_NO_PK PRIMARY KEY(BKF_NO));



CREATE SEQUENCE BKF_NO_SEQ
INCREMENT BY 1 
START WITH 100 
NOMAXVALUE
NOCYCLE
NOCACHE;

------INSERT先寫在這裡--------
INSERT INTO BK_FUNCTION(BKF_NO, BKF_NAME, BKF_DSB, BKF_STATE) 
VALUES(BKF_NO_SEQ.NEXTVAL, '管理員工', '管理後台帳號、管理後台帳號權限' ,'ON');
INSERT INTO BK_FUNCTION(BKF_NO, BKF_NAME, BKF_DSB, BKF_STATE) 
VALUES(BKF_NO_SEQ.NEXTVAL, '審核權限', '審核房仲註冊、審核廠商註冊' ,'ON');
INSERT INTO BK_FUNCTION(BKF_NO, BKF_NAME, BKF_DSB, BKF_STATE) 
VALUES(BKF_NO_SEQ.NEXTVAL, '維護房屋資料', '房屋資料更新檢視、房屋資料爬蟲開關' ,'TEST');
INSERT INTO BK_FUNCTION(BKF_NO, BKF_NAME, BKF_DSB, BKF_STATE) 
VALUES(BKF_NO_SEQ.NEXTVAL, '管理檢舉', '審核檢舉房仲、審核檢舉廠商' ,'ON');
INSERT INTO BK_FUNCTION(BKF_NO, BKF_NAME, BKF_DSB, BKF_STATE) 
VALUES(BKF_NO_SEQ.NEXTVAL, '管理NEWS', '管理房市最新消息、管理系統公告、管理促銷資訊' ,'ON');
INSERT INTO BK_FUNCTION(BKF_NO, BKF_NAME, BKF_DSB, BKF_STATE)
VALUES(BKF_NO_SEQ.NEXTVAL, '管理廣告', '審核廠商廣告申請刊登廣告撤銷廣告' ,'ON');
INSERT INTO BK_FUNCTION(BKF_NO, BKF_NAME, BKF_DSB, BKF_STATE)
VALUES(BKF_NO_SEQ.NEXTVAL, '管理常見問題', '更新問題' ,'ON');

------------------------------
CREATE TABLE EMPLOYEE_AUTH(
EMP_NO VARCHAR2(10) NOT NULL,
BKF_NO NUMBER(10) NOT NULL,
EMAU_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
EMAU_EDITOR VARCHAR2(10),
CONSTRAINT EMP_NO_FK FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEE(EMP_NO),
CONSTRAINT BKF_NO_FK FOREIGN KEY (BKF_NO) REFERENCES BK_FUNCTION
(BKF_NO),
CONSTRAINT EMPLOYEE_AUTH_PK PRIMARY KEY(EMP_NO,BKF_NO));
------INSERT先寫在這裡--------
INSERT INTO EMPLOYEE_AUTH(EMP_NO, BKF_NO,EMAU_EDITOR) 
VALUES('EM00000003', 100, 'EM00000001');
INSERT INTO EMPLOYEE_AUTH(EMP_NO, BKF_NO,EMAU_EDITOR) 
VALUES('EM00000003', 101, 'EM00000001');
INSERT INTO EMPLOYEE_AUTH(EMP_NO, BKF_NO,EMAU_EDITOR) 
VALUES('EM00000003', 102, 'EM00000001');

-----員工的世界-複製到這邊-請按下COMMIT-------
COMMIT;

-------------- 檢舉商品案件 (要先建 EMPLOYEE 表格) --------------
CREATE TABLE REPORTPRODUCT (
RP_NO          VARCHAR2(10) NOT NULL,
MEM_NO         VARCHAR2(10) NOT NULL,
PRD_NO         VARCHAR2(10) NOT NULL,
EMP_NO         VARCHAR2(10),
RP_REASON      VARCHAR2(200),
RP_RESULT      VARCHAR2(200),
RP_STATE       VARCHAR2(10),
RP_TIME        TIMESTAMP,
CONSTRAINT RP_PK PRIMARY KEY(RP_NO),
CONSTRAINT RP_MEM_FK FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO),
CONSTRAINT RP_PRDT_FK FOREIGN KEY(PRD_NO) REFERENCES PRODUCT(PRD_NO),
CONSTRAINT RP_EMP_FK FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO) );

CREATE SEQUENCE RP_SEQ
INCREMENT BY 1 
START WITH 1 
NOCACHE;
--------------------------------
--檢舉商品案件尚未 INSERT 假資料
--------------------------------


-------- 檢舉房仲案件 (要先建 EMPLOYEE 表格) --------
CREATE TABLE REPORTREALTOR (
RR_NO         VARCHAR2(10) NOT NULL,
MEM_NO        VARCHAR2(10) NOT NULL,
RTR_NO        VARCHAR2(10) NOT NULL,
EMP_NO        VARCHAR2(10),
RR_REASON     VARCHAR2(200),
RR_RESULT     VARCHAR2(200),
RR_STATE      VARCHAR2(10),
RR_TIME       TIMESTAMP,
CONSTRAINT RR_PK PRIMARY KEY(RR_NO),
CONSTRAINT RR_MEM_FK FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO),
CONSTRAINT RR_RTR_FK FOREIGN KEY(RTR_NO) REFERENCES REALTOR(RTR_NO),
CONSTRAINT RR_EMP_FK FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO) );

CREATE SEQUENCE RR_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;
--------------------------------
--檢舉房仲案件尚未 INSERT 假資料
--------------------------------
COMMIT;
-----------------------------------------------------------------------------YYY---------------------------------

CREATE TABLE PRODUCT_ORDER(
PDO_NO VARCHAR2(15) NOT NULL,
MEM_NO VARCHAR2(10) NOT NULL,
SLR_NO VARCHAR2(10) NOT NULL,
PDO_STAT VARCHAR2(20),
PDO_RESR_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
SLR_RATE NUMBER(2),
MEM_RATE NUMBER(2),
MEM_REVIEW VARCHAR2(100),
PDO_PARAMS CLOB,
CP_NO VARCHAR2(10),
CONSTRAINT PDO_NO_PK PRIMARY KEY(PDO_NO),
CONSTRAINT MEM_NO_FK FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO),
CONSTRAINT SLR_NO_FK FOREIGN KEY (SLR_NO) REFERENCES SELLER(SLR_NO));



CREATE SEQUENCE PDO_NO_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

------INSERT先寫在這裡--------
INSERT INTO PRODUCT_ORDER(PDO_NO, MEM_NO, SLR_NO, PDO_STAT)
VALUES('OD'||TO_CHAR(SYSDATE,'RRMMDD')||'-'||(LPAD(TO_CHAR(PDO_NO_SEQ.NEXTVAL),6,'0')), 'MB00000001', 'SL00000001' ,'ORDER');
INSERT INTO PRODUCT_ORDER(PDO_NO, MEM_NO, SLR_NO, PDO_STAT)
VALUES('OD'||TO_CHAR(SYSDATE,'RRMMDD')||'-'||(LPAD(TO_CHAR(PDO_NO_SEQ.NEXTVAL),6,'0')), 'MB00000001', 'SL00000001' ,'ORDER');
INSERT INTO PRODUCT_ORDER(PDO_NO, MEM_NO, SLR_NO, PDO_STAT)
VALUES('OD'||TO_CHAR(SYSDATE,'RRMMDD')||'-'||(LPAD(TO_CHAR(PDO_NO_SEQ.NEXTVAL),6,'0')), 'MB00000002', 'SL00000001' ,'ORDER');
INSERT INTO PRODUCT_ORDER(PDO_NO, MEM_NO, SLR_NO, PDO_STAT)
VALUES('OD'||TO_CHAR(SYSDATE,'RRMMDD')||'-'||(LPAD(TO_CHAR(PDO_NO_SEQ.NEXTVAL),6,'0')), 'MB00000002', 'SL00000002' ,'ORDER');
INSERT INTO PRODUCT_ORDER(PDO_NO, MEM_NO, SLR_NO, PDO_STAT)
VALUES('OD'||TO_CHAR(SYSDATE,'RRMMDD')||'-'||(LPAD(TO_CHAR(PDO_NO_SEQ.NEXTVAL),6,'0')), 'MB00000003', 'SL00000003' ,'ORDER');
INSERT INTO PRODUCT_ORDER(PDO_NO, MEM_NO, SLR_NO, PDO_STAT)
VALUES('OD'||TO_CHAR(SYSDATE,'RRMMDD')||'-'||(LPAD(TO_CHAR(PDO_NO_SEQ.NEXTVAL),6,'0')), 'MB00000002', 'SL00000003' ,'DELIVER');
INSERT INTO PRODUCT_ORDER(PDO_NO, MEM_NO, SLR_NO, PDO_STAT)
VALUES('OD'||TO_CHAR(SYSDATE,'RRMMDD')||'-'||(LPAD(TO_CHAR(PDO_NO_SEQ.NEXTVAL),6,'0')), 'MB00000002', 'SL00000004' ,'CANCEL');
-------------------------------------------------------------


CREATE TABLE ORDER_DETAIL(
PDO_NO VARCHAR2(15) NOT NULL,
PRD_NO VARCHAR2(10) NOT NULL,
ODER_UNI_PRICE NUMBER(10),
ODER_QUANTITY NUMBER(10),
CONSTRAINT PDO_NO_FK FOREIGN KEY (PDO_NO) REFERENCES PRODUCT_ORDER(PDO_NO),
CONSTRAINT PRD_NO_FK FOREIGN KEY (PRD_NO) REFERENCES PRODUCT(PRD_NO),
CONSTRAINT ORDER_DETAIL_PK PRIMARY KEY(PDO_NO,PRD_NO)
);
------INSERT先寫在這裡--------
INSERT INTO ORDER_DETAIL(PDO_NO, PRD_NO, ODER_UNI_PRICE, ODER_QUANTITY) 
VALUES('OD'||TO_CHAR(SYSDATE,'RRMMDD')||'-000001', 'PD00000020', 500000000 ,10);
INSERT INTO ORDER_DETAIL(PDO_NO, PRD_NO, ODER_UNI_PRICE, ODER_QUANTITY) 
VALUES('OD'||TO_CHAR(SYSDATE,'RRMMDD')||'-000002', 'PD00000011', 500000000 ,10);
COMMIT;



-------------子楷-----------------------------------

CREATE SEQUENCE HOUSE_SEQUENCE
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOMAXVALUE;

CREATE SEQUENCE HOUSEIMAGES_SEQUENCE
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOMAXVALUE;

CREATE SEQUENCE ADVERTISEMENT_SEQUANCE
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOMAXVALUE;


CREATE TABLE HOUSEINFO(
HOUSE_NO VARCHAR2(100) NOT NULL PRIMARY KEY,
RE_NO VARCHAR2(10) NOT NULL,
HOUSE_SERIAL_NUMBER VARCHAR2(100) NOT NULL,
TITLE VARCHAR2(100) NOT NULL,
LOCATION VARCHAR2(100) NOT NULL,
PRICE VARCHAR2(100) NOT NULL,
TOTAL_PINGS NUMBER(10,2) NOT NULL,
MAIN_PINGS NUMBER(10,2),
AMENITY_PINGS NUMBER(10,2),
ACCESSORY_PINGS NUMBER(10,2),
FLOOR VARCHAR2(100),
AGE NUMBER(10,2),
PATTERN VARCHAR2(100),
ORIENTATION VARCHAR2(100),
BUILDING_MATERIALS VARCHAR2(100),
PARKING_SPACE VARCHAR2(100),
CLASSIFICATION_OF_LAND VARCHAR2(100),
LAND_PINGS NUMBER(10,2),
DATA_INFO CLOB,
MAIN_IMG BLOB,
LAT NUMBER(10,5),
LNG NUMBER(10,5),
HOUSE_STATES VARCHAR2(100),
INSERT_TIME TIMESTAMP,
FINAL_UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT FK_HOUSEINFO_REALESTATE FOREIGN KEY(RE_NO) REFERENCES REALESTATE(RE_NO)
);