------------ 房仲公司 --------------
CREATE TABLE REALESTATE (
RE_NO         VARCHAR2(10) NOT NULL,
RE_NAME       VARCHAR2(40) NOT NULL,
CONSTRAINT RE_PK PRIMARY KEY(RE_NO) );

CREATE SEQUENCE RE_SEQ 
INCREMENT BY 1 
START WITH 1 
NOCACHE;

INSERT INTO REALESTATE VALUES ('RE'||(LPAD(TO_CHAR(RE_SEQ.NEXTVAL),8,'0')),'信義房屋');
INSERT INTO REALESTATE VALUES ('RE'||(LPAD(TO_CHAR(RE_SEQ.NEXTVAL),8,'0')),'永慶房屋');
INSERT INTO REALESTATE VALUES ('RE'||(LPAD(TO_CHAR(RE_SEQ.NEXTVAL),8,'0')),'東森房屋');

------------ 房屋 --------------
CREATE SEQUENCE HOUSE_SEQUENCE
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOMAXVALUE;

CREATE SEQUENCE HOUSEIMAGES_SEQUENCE
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOMAXVALUE;


CREATE TABLE HOUSEINFO(
HOUSE_NO VARCHAR2(100) NOT NULL PRIMARY KEY,
RE_NO VARCHAR2(10) NOT NULL,
HOUSE_SERIAL_NUMBER VARCHAR2(100) NOT NULL,
TITLE VARCHAR2(100) NOT NULL,
LOCATION VARCHAR2(100) NOT NULL,
PRICE VARCHAR2(100) NOT NULL,
TOTAL_PINGS NUMBER(10,2) NOT NULL,
MAIN_PINGS NUMBER(10,2),
AMENITY_PINGS NUMBER(10,2),
ACCESSORY_PINGS NUMBER(10,2),
FLOOR VARCHAR2(100),
AGE NUMBER(10,2),
PATTERN VARCHAR2(100),
ORIENTATION VARCHAR2(100),
BUILDING_MATERIALS VARCHAR2(100),
PARKING_SPACE VARCHAR2(100),
CLASSIFICATION_OF_LAND VARCHAR2(100),
LAND_PINGS NUMBER(10,2),
DATA_INFO CLOB,
MAIN_IMG BLOB,
LAT NUMBER(10,5),
LNG NUMBER(10,5),
HOUSE_STATES VARCHAR2(100),
INSERT_TIME TIMESTAMP,
FINAL_UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT FK_HOUSEINFO_REALESTATE FOREIGN KEY(RE_NO) REFERENCES REALESTATE(RE_NO)
);

INSERT INTO HOUSEINFO(HOUSE_NO, RE_NO, HOUSE_SERIAL_NUMBER, TITLE,LOCATION,PRICE,TOTAL_PINGS) 
VALUES('HSE'||LPAD(to_char(house_sequence.nextval),8,'0'), 'RE00000002', '2764617' ,'仁愛電梯兩房車位 - 仁愛路林蔭 15年內電梯二房','台北市中正區仁愛路二段','2,498',50.12);
INSERT INTO HOUSEINFO(HOUSE_NO, RE_NO, HOUSE_SERIAL_NUMBER, TITLE,LOCATION,PRICE,TOTAL_PINGS) 
VALUES('HSE'||LPAD(to_char(house_sequence.nextval),8,'0'), 'RE00000002', 'YC946209' ,'博嘉靜巷雅緻三房 - 邊間採光明亮，住家環境安靜','台北市文山區木柵路四段','1,380',37.08);
INSERT INTO HOUSEINFO(HOUSE_NO, RE_NO, HOUSE_SERIAL_NUMBER, TITLE,LOCATION,PRICE,TOTAL_PINGS) 
VALUES('HSE'||LPAD(to_char(house_sequence.nextval),8,'0'), 'RE00000001', '4546L' ,'大戶移居河濱生活(34546L)','台北市文山區樟新街','4,120',71.09);

----------------------------------------------------------------------------------------------------------------------------
CREATE TABLE HOUSEIMAGES(
IMG_NO VARCHAR2(100) NOT NULL PRIMARY KEY,
HOUSE_NO VARCHAR2(100) NOT NULL,
IMG BLOB,
STATE VARCHAR2(50) NOT NULL,
INSERT_TIME TIMESTAMP,
CONSTRAINT FK_HOUSEIMG_HOUSEINFO FOREIGN KEY (HOUSE_NO) REFERENCES HOUSEINFO (HOUSE_NO)
);

commit;